// 英文语言变体 — BrandStyle.botw（希卡之石）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.botw）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enBotw = BrandStrings(
  appTitle: 'Duoyi · Sheikah Slate',
  greetingMorning: 'First light, Link',
  greetingNoon: 'High noon in Hyrule',
  greetingAfternoon: 'Golden afternoon light',
  greetingEvening: 'Night falls on Hyrule',
  navToday: 'Dawn',
  navTodo: 'Runes',
  navHabit: 'Training',
  navCalendar: 'Slate',
  navFocus: 'Attune',
  navMine: 'Sheikah',
  navWidget: 'Sheikah Scope',
  todoTitle: 'Rune Registry',
  todoMatrixView: 'Rune Matrix',
  todoListView: 'Rune Index',
  todoEmpty: 'The Slate bears no runes',
  todoAddAction: 'Carve a New Rune',
  todoCreateTitle: 'New Rune',
  quadrantQ1Label: 'Attune Now',
  quadrantQ1Sub: 'Danger brooks no delay',
  quadrantQ2Label: 'Long Expeditions',
  quadrantQ2Sub: 'Steady strides',
  quadrantQ3Label: 'Allied Hands',
  quadrantQ3Sub: 'A companion can carry it',
  quadrantQ4Label: 'Sealed Archive',
  quadrantQ4Sub: 'Low priority',
  subtasksHeading: 'Sub-Runes',
  habitTitle: 'Daily Training',
  habitTabToday: 'Today\'s Training',
  habitTabHeatmap: 'Training Heat',
  habitEmpty: 'No training logged yet',
  habitAddAction: 'Record New Training',
  habitCreateTitle: 'New Training',
  habitWeekOverview: 'This Week\'s Training',
  habitHeatmapHeading: 'Training Heatmap',
  habitStreakLabel: 'Streak',
  habitTodayDone: 'done today',
  calendarTitle: 'Sheikah Slate',
  calendarTabMonth: 'Month',
  calendarTabWeek: 'Week',
  calendarTabDay: 'Day',
  calendarEmpty: 'The Slate is blank this day',
  calendarQuickAddTitle: 'Carve into this day',
  focusTitle: 'Attunement',
  focusTabTimer: 'Attune',
  focusTabHistory: 'Log',
  focusStateFocus: 'Attuning',
  focusStateShortBreak: 'Stamina Returns',
  focusStateLongBreak: 'Deep Recovery',
  focusCompletedSuffix: 'attunements achieved',
  focusEmpty: 'No attunement has begun yet',
  focusWhiteNoiseOn: 'Shrine Ambience ON',
  focusWhiteNoiseOff: 'Shrine Ambience OFF',
  focusTaskLinkLabel: 'Linked Rune',
  mineTitle: 'Sheikah Stone',
  mineProductivityScore: 'Sheikah Rank',
  mineSectionShortcuts: 'Shortcuts',
  mineSectionSettings: 'System',
  mineAllTodos: 'All Runes',
  mineAllHabits: 'All Training',
  mineDataDetail: 'Sheikah Archives',
  mineThemeLabel: 'Theme Style',
  mineNotificationsLabel: 'Notification Preferences',
  mineCloudSyncLabel: 'Cloud Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Attunement Complete',
  notifPomodoroDoneBody: 'Energy spent — rest a while and recover.',
  notifBreakDoneTitle: 'Energy Restored',
  notifBreakDoneBody: 'Ready to begin the next attunement',
  notifTodoDueTitle: 'Rune Expiring Soon',
  notifHabitRemindTitle: 'Training Reminder',
);
