// 英文语言变体 — BrandStyle.defaultBrand（默认主题）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.defaultBrand）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enDefaultBrand = BrandStrings(
  appTitle: 'Duoyi',
  greetingMorning: 'Good morning',
  greetingNoon: 'Good day',
  greetingAfternoon: 'Good afternoon',
  greetingEvening: 'Good evening',
  navToday: 'Today',
  navTodo: 'To-Do',
  navHabit: 'Habits',
  navCalendar: 'Calendar',
  navFocus: 'Focus',
  navMine: 'Me',
  navWidget: 'Widgets',
  todoTitle: 'To-Do List',
  todoMatrixView: 'Quadrants',
  todoListView: 'List',
  todoEmpty: 'No tasks yet',
  todoAddAction: 'Add your first task',
  todoCreateTitle: 'New task',
  quadrantQ1Label: 'Important & Urgent',
  quadrantQ1Sub: 'Do now',
  quadrantQ2Label: 'Important, Not Urgent',
  quadrantQ2Sub: 'Schedule',
  quadrantQ3Label: 'Urgent, Not Important',
  quadrantQ3Sub: 'Delegate',
  quadrantQ4Label: 'Not Important, Not Urgent',
  quadrantQ4Sub: 'Do less',
  subtasksHeading: 'Subtasks',
  habitTitle: 'Habits',
  habitTabToday: 'Today',
  habitTabHeatmap: 'Heatmap',
  habitEmpty: 'No habits to check in today',
  habitAddAction: 'Add habit',
  habitCreateTitle: 'New habit',
  habitWeekOverview: 'This week',
  habitHeatmapHeading: 'Cumulative check-in heat',
  habitStreakLabel: 'Streak',
  habitTodayDone: 'Done',
  calendarTitle: 'Calendar',
  calendarTabMonth: 'Month',
  calendarTabWeek: 'Week',
  calendarTabDay: 'Day',
  calendarEmpty: 'Nothing planned for this day',
  calendarQuickAddTitle: 'New to-do',
  focusTitle: 'Pomodoro Focus',
  focusTabTimer: 'Timer',
  focusTabHistory: 'History',
  focusStateFocus: 'Focus',
  focusStateShortBreak: 'Short break',
  focusStateLongBreak: 'Long break',
  focusCompletedSuffix: 'focus sessions',
  focusEmpty: 'No focus sessions yet',
  focusWhiteNoiseOn: 'White noise ON',
  focusWhiteNoiseOff: 'White noise OFF',
  focusTaskLinkLabel: 'Linked task',
  mineTitle: 'Me',
  mineProductivityScore: 'Overall score',
  mineSectionShortcuts: 'Shortcuts',
  mineSectionSettings: 'Settings',
  mineAllTodos: 'All to-dos',
  mineAllHabits: 'All habits',
  mineDataDetail: 'Data details',
  mineThemeLabel: 'Theme',
  mineNotificationsLabel: 'Reminders',
  mineCloudSyncLabel: 'Cloud sync',
  mineDataMgmtLabel: 'Data management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Pomodoro complete',
  notifPomodoroDoneBody: 'You finished a focus session — take a break!',
  notifBreakDoneTitle: 'Break finished',
  notifBreakDoneBody: 'Ready for your next focus session?',
  notifTodoDueTitle: "Today's reminders",
  notifHabitRemindTitle: 'Habit check-in reminder',
);
