// 英文语言变体 — BrandStyle.genshin（原神）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.genshin）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enGenshin = BrandStrings(
  appTitle: 'Duoyi · Teyvat Almanac',
  greetingMorning: 'Dawn breaks, Traveler',
  greetingNoon: 'The elements stir at midday',
  greetingAfternoon: 'Fair skies this afternoon',
  greetingEvening: 'Night falls over Teyvat, Traveler',
  navToday: 'Journey',
  navTodo: 'Adventure',
  navHabit: 'Dailies',
  navCalendar: 'Journal',
  navFocus: 'Focus',
  navMine: 'Gear',
  navWidget: 'Vista',
  todoTitle: 'Commissions',
  todoMatrixView: 'Elemental Matrix',
  todoListView: 'Commission List',
  todoEmpty: 'The Adventurers\' Guild has no commissions right now',
  todoAddAction: 'Accept New Commission',
  todoCreateTitle: 'New Commission',
  quadrantQ1Label: 'Urgent Dispatch',
  quadrantQ1Sub: 'Elemental Imbalance',
  quadrantQ2Label: 'Long-Term Expedition',
  quadrantQ2Sub: 'Steady Progress',
  quadrantQ3Label: 'Support Commission',
  quadrantQ3Sub: 'Safe to Delegate',
  quadrantQ4Label: 'Set Aside',
  quadrantQ4Sub: 'Low Value for Now',
  subtasksHeading: 'Objectives',
  habitTitle: 'Daily Commissions',
  habitTabToday: 'Today\'s Commissions',
  habitTabHeatmap: 'Dailies Trail',
  habitEmpty: 'No dailies registered with the Adventurers\' Guild yet',
  habitAddAction: 'Register a New Daily',
  habitCreateTitle: 'New Daily',
  habitWeekOverview: 'This Week\'s Dailies',
  habitHeatmapHeading: 'Adventure Trail Heatmap',
  habitStreakLabel: 'Streak',
  habitTodayDone: 'Completed Today',
  calendarTitle: 'Adventure Log',
  calendarTabMonth: 'Month',
  calendarTabWeek: 'Week',
  calendarTabDay: 'Day',
  calendarEmpty: 'No adventures logged this day',
  calendarQuickAddTitle: 'Accept Commissions for This Day',
  focusTitle: 'Deep Meditation',
  focusTabTimer: 'Meditation',
  focusTabHistory: 'Records',
  focusStateFocus: 'Focusing',
  focusStateShortBreak: 'Elemental Recharge',
  focusStateLongBreak: 'Extended Recharge',
  focusCompletedSuffix: 'meditations completed',
  focusEmpty: 'Your meditation journey has yet to begin',
  focusWhiteNoiseOn: 'Anemo Whispers ON',
  focusWhiteNoiseOff: 'Anemo Whispers OFF',
  focusTaskLinkLabel: 'Linked Commission',
  mineTitle: 'Gear & Archive',
  mineProductivityScore: 'Adventure Rank',
  mineSectionShortcuts: 'Quick Access',
  mineSectionSettings: 'System',
  mineAllTodos: 'All Commissions',
  mineAllHabits: 'All Dailies',
  mineDataDetail: 'Adventure Archive',
  mineThemeLabel: 'Theme Style',
  mineNotificationsLabel: 'Notification Preferences',
  mineCloudSyncLabel: 'Cloud Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Meditation Complete',
  notifPomodoroDoneBody: 'Elemental energy fully recharged — time for a rest.',
  notifBreakDoneTitle: 'Recharge Complete',
  notifBreakDoneBody: 'Ready to set out again?',
  notifTodoDueTitle: 'Commission Due Soon',
  notifHabitRemindTitle: 'Dailies Reminder',
);
