// 英文语言变体 — BrandStyle.re0（Re:从零开始）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.re0）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enRe0 = BrandStrings(
  appTitle: 'Duoyi · Lugunica',
  greetingMorning: 'Dawn has broken, Witch',
  greetingNoon: 'The Light of Noon',
  greetingAfternoon: 'Pact of the Afternoon',
  greetingEvening: 'Night deepens, Returner',
  navToday: 'Daybreak',
  navTodo: 'Spells',
  navHabit: 'Pacts',
  navCalendar: 'Corridor',
  navFocus: 'Chants',
  navMine: 'Trials',
  navWidget: 'Sanctuary',
  todoTitle: 'Spell Ledger',
  todoMatrixView: 'Fourfold Array',
  todoListView: 'Spell Codex',
  todoEmpty: 'The spell scrolls lie empty',
  todoAddAction: 'Inscribe a New Spell',
  todoCreateTitle: 'New Spell',
  quadrantQ1Label: 'Chant at Once',
  quadrantQ1Sub: 'Urgent and vital',
  quadrantQ2Label: 'Weave the Magic',
  quadrantQ2Sub: 'Vital, not urgent',
  quadrantQ3Label: 'Familiars\' Errands',
  quadrantQ3Sub: 'Urgent, not vital',
  quadrantQ4Label: 'Cast into Shadow',
  quadrantQ4Sub: 'Neither urgent nor vital',
  subtasksHeading: 'Sub-Spells',
  habitTitle: 'Daily Pacts',
  habitTabToday: 'Today\'s Pacts',
  habitTabHeatmap: 'Pact Heat',
  habitEmpty: 'No pact has been sealed yet',
  habitAddAction: 'Seal a New Pact',
  habitCreateTitle: 'New Pact',
  habitWeekOverview: 'Pacts Fulfilled This Week',
  habitHeatmapHeading: 'Cumulative Pact Fulfillment',
  habitStreakLabel: 'Fulfillment Streak',
  habitTodayDone: 'Honored Today',
  calendarTitle: 'Corridor of Memories',
  calendarTabMonth: 'Moonphase',
  calendarTabWeek: 'Week',
  calendarTabDay: 'This Day',
  calendarEmpty: 'The corridor stands empty on this day',
  calendarQuickAddTitle: 'Inscribe a Spell for This Day',
  focusTitle: 'Rite of Chanting',
  focusTabTimer: 'Chant',
  focusTabHistory: 'Echoes',
  focusStateFocus: 'Chanting',
  focusStateShortBreak: 'Mana Reflow',
  focusStateLongBreak: 'Deep Slumber',
  focusCompletedSuffix: 'Chants Fulfilled',
  focusEmpty: 'No chant has left an echo yet',
  focusWhiteNoiseOn: 'Arcane Murmur ON',
  focusWhiteNoiseOff: 'Arcane Murmur OFF',
  focusTaskLinkLabel: 'Linked Spell',
  mineTitle: 'Trial Grounds',
  mineProductivityScore: 'Mana Rating',
  mineSectionShortcuts: 'Quick Pacts',
  mineSectionSettings: 'Magecraft Settings',
  mineAllTodos: 'All Spells',
  mineAllHabits: 'All Pacts',
  mineDataDetail: 'Mana Dossier',
  mineThemeLabel: 'Theme Style',
  mineNotificationsLabel: 'Magic Reminders',
  mineCloudSyncLabel: 'Memory Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Chant Complete',
  notifPomodoroDoneBody: 'Your mana is spent — rest a while',
  notifBreakDoneTitle: 'Mana Restored',
  notifBreakDoneBody: 'Ready to begin the next chant?',
  notifTodoDueTitle: 'A Spell Nears Its Expiry',
  notifHabitRemindTitle: 'Pact Reminder',
);
