// 英文语言变体 — BrandStyle.starRail（星穹铁道）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.starRail）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enStarRail = BrandStrings(
  appTitle: 'Duoyi · Express Log',
  greetingMorning: 'Good morning, Trailblazer',
  greetingNoon: 'Midday Trailblazing hours',
  greetingAfternoon: 'An afternoon warp',
  greetingEvening: 'We\'ve sailed into deep space, Trailblazer',
  navToday: 'Excursion',
  navTodo: 'Trailblaze',
  navHabit: 'Traces',
  navCalendar: 'Timetable',
  navFocus: 'Warp',
  navMine: 'Data Bank',
  navWidget: 'Star Chart',
  todoTitle: 'Trailblaze Missions',
  todoMatrixView: 'Starmap Array',
  todoListView: 'Mission Log',
  todoEmpty: 'The Express manifest is empty',
  todoAddAction: 'Chart a new mission',
  todoCreateTitle: 'New Mission',
  quadrantQ1Label: 'Urgent Trailblazing',
  quadrantQ1Sub: 'Imaginary imbalance',
  quadrantQ2Label: 'Long-Haul Routes',
  quadrantQ2Sub: 'Rails laid ahead',
  quadrantQ3Label: 'Crew Assistance',
  quadrantQ3Sub: 'Delegate to the crew',
  quadrantQ4Label: 'Shelved Among the Stars',
  quadrantQ4Sub: 'Low value',
  subtasksHeading: 'Minor Objectives',
  habitTitle: 'Daily Traces',
  habitTabToday: 'Today\'s Traces',
  habitTabHeatmap: 'Journey Heat',
  habitEmpty: 'No Traces recorded yet',
  habitAddAction: 'Record a new Trace',
  habitCreateTitle: 'New Trace',
  habitWeekOverview: 'This Week\'s Traces',
  habitHeatmapHeading: 'Journey Heatmap',
  habitStreakLabel: 'Trace Streak',
  habitTodayDone: 'Done for today',
  calendarTitle: 'Express Timetable',
  calendarTabMonth: 'Month',
  calendarTabWeek: 'Week',
  calendarTabDay: 'Day',
  calendarEmpty: 'The Express doesn\'t stop here today',
  calendarQuickAddTitle: 'Assign a mission for this stop',
  focusTitle: 'Warp Bay',
  focusTabTimer: 'Warp',
  focusTabHistory: 'Voyage Log',
  focusStateFocus: 'Warping',
  focusStateShortBreak: 'Short Stopover',
  focusStateLongBreak: 'Long Stopover',
  focusCompletedSuffix: 'warps completed',
  focusEmpty: 'No warps started yet',
  focusWhiteNoiseOn: 'Deep-Space Static ON',
  focusWhiteNoiseOff: 'Deep-Space Static OFF',
  focusTaskLinkLabel: 'Linked Mission',
  mineTitle: 'Data Bank',
  mineProductivityScore: 'Trailblaze Level',
  mineSectionShortcuts: 'Quick Links',
  mineSectionSettings: 'System',
  mineAllTodos: 'All Missions',
  mineAllHabits: 'All Traces',
  mineDataDetail: 'Record Details',
  mineThemeLabel: 'Theme',
  mineNotificationsLabel: 'Notifications',
  mineCloudSyncLabel: 'Cloud Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Warp Complete',
  notifPomodoroDoneBody: 'Energy depleted — time for a brief stop',
  notifBreakDoneTitle: 'Stopover Complete',
  notifBreakDoneBody: 'Ready for your next warp',
  notifTodoDueTitle: 'Mission Due Soon',
  notifHabitRemindTitle: 'Trace Reminder',
);
