// 英文语言变体 — BrandStyle.wuthering（鸣潮）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.wuthering）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enWuthering = BrandStrings(
  appTitle: 'Duoyi · Resonance Chronicle',
  greetingMorning: 'Good morning, Rover',
  greetingNoon: 'Tidesong at Noon',
  greetingAfternoon: 'Afternoon Echoes',
  greetingEvening: 'The Night Tide Rises',
  navToday: 'Morning Tide',
  navTodo: 'Voiceprints',
  navHabit: 'Echoes',
  navCalendar: 'Tides',
  navFocus: 'Resonance',
  navMine: 'Archive',
  navWidget: 'Sonar',
  todoTitle: 'Voiceprint List',
  todoMatrixView: 'Voiceprint Matrix',
  todoListView: 'Voiceprint Ledger',
  todoEmpty: 'No voiceprints captured yet',
  todoAddAction: 'Capture a New Voiceprint',
  todoCreateTitle: 'New Voiceprint',
  quadrantQ1Label: 'Immediate Tuning',
  quadrantQ1Sub: 'Sharp Resonance',
  quadrantQ2Label: 'Enduring Soundfield',
  quadrantQ2Sub: 'Steady Frequency',
  quadrantQ3Label: 'Concerto Tuning',
  quadrantQ3Sub: 'Delegable to Companions',
  quadrantQ4Label: 'Dampened Frequency',
  quadrantQ4Sub: 'Can Be Reduced',
  subtasksHeading: 'Sub-Voiceprints',
  habitTitle: 'Daily Echoes',
  habitTabToday: 'Today\'s Echoes',
  habitTabHeatmap: 'Echo Heat',
  habitEmpty: 'No echoes captured yet',
  habitAddAction: 'Record a New Echo',
  habitCreateTitle: 'New Echo',
  habitWeekOverview: 'This Week\'s Echoes',
  habitHeatmapHeading: 'Echo Heat Map',
  habitStreakLabel: 'Echo Streak',
  habitTodayDone: 'Resonated Today',
  calendarTitle: 'Tide Chart',
  calendarTabMonth: 'Month',
  calendarTabWeek: 'Week',
  calendarTabDay: 'Day',
  calendarEmpty: 'No tides on this day',
  calendarQuickAddTitle: 'Write a Voiceprint for This Day',
  focusTitle: 'Resonance Chamber',
  focusTabTimer: 'Resonance',
  focusTabHistory: 'Echo Log',
  focusStateFocus: 'Resonating',
  focusStateShortBreak: 'Field Cooldown',
  focusStateLongBreak: 'Deep Cooldown',
  focusCompletedSuffix: 'Resonances Achieved',
  focusEmpty: 'No resonances recorded yet',
  focusWhiteNoiseOn: 'Tidal Noise ON',
  focusWhiteNoiseOff: 'Tidal Noise OFF',
  focusTaskLinkLabel: 'Linked Voiceprint',
  mineTitle: 'Rover\'s Archive',
  mineProductivityScore: 'Resonance Tier',
  mineSectionShortcuts: 'Quick Access',
  mineSectionSettings: 'System',
  mineAllTodos: 'All Voiceprints',
  mineAllHabits: 'All Echoes',
  mineDataDetail: 'Archive Details',
  mineThemeLabel: 'Theme Style',
  mineNotificationsLabel: 'Notification Preferences',
  mineCloudSyncLabel: 'Cloud Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Resonance Complete',
  notifPomodoroDoneBody: 'The soundfield dissipates — time to cool down',
  notifBreakDoneTitle: 'Cooldown Complete',
  notifBreakDoneBody: 'Ready to resonate again?',
  notifTodoDueTitle: 'A Voiceprint Is Fading',
  notifHabitRemindTitle: 'Echo Reminder',
);
