// 英文语言变体 — BrandStyle.yanyun（燕云十六声）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.yanyun）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enYanyun = BrandStrings(
  appTitle: 'Duoyi · Jianghu Chronicles',
  greetingMorning: 'Dawn breaks faintly, young hero',
  greetingNoon: 'High noon on the jianghu',
  greetingAfternoon: 'Tea scents the afternoon',
  greetingEvening: 'Nightfall settles over the jianghu',
  navToday: 'Dawn Bell',
  navTodo: 'Deeds',
  navHabit: 'Cultivation',
  navCalendar: 'Almanac',
  navFocus: 'Meditation',
  navMine: 'Satchel',
  navWidget: 'Missive',
  todoTitle: 'Deeds of the Jianghu',
  todoMatrixView: 'Yin-Yang Formation',
  todoListView: 'Roster',
  todoEmpty: 'All is quiet in the jianghu',
  todoAddAction: 'Record a new deed',
  todoCreateTitle: 'New Deed',
  quadrantQ1Label: 'Strike at Once',
  quadrantQ1Sub: 'Swift wind, raging fire',
  quadrantQ2Label: 'Plan at Length',
  quadrantQ2Sub: 'Advance with patience',
  quadrantQ3Label: 'Entrust to Disciples',
  quadrantQ3Sub: 'Another hand may act for you',
  quadrantQ4Label: 'Scatter on the Wind',
  quadrantQ4Sub: 'Not worth the trouble',
  subtasksHeading: 'Fine Details',
  habitTitle: 'Daily Cultivation',
  habitTabToday: 'Today’s Training',
  habitTabHeatmap: 'Kung Fu Heat',
  habitEmpty: 'No daily training pledged yet',
  habitAddAction: 'Pledge a daily practice',
  habitCreateTitle: 'New Daily Practice',
  habitWeekOverview: 'This Week’s Training',
  habitHeatmapHeading: 'Cultivation Heat Map',
  habitStreakLabel: 'Unbroken Cultivation',
  habitTodayDone: 'Diligent this day',
  calendarTitle: 'Almanac',
  calendarTabMonth: 'Moon Phase',
  calendarTabWeek: 'Seven Days',
  calendarTabDay: 'This Day',
  calendarEmpty: 'No stirrings in the jianghu this day',
  calendarQuickAddTitle: 'Jot an entry for this day',
  focusTitle: 'Meditation',
  focusTabTimer: 'Meditation',
  focusTabHistory: 'Practice Log',
  focusStateFocus: 'In Deep Meditation',
  focusStateShortBreak: 'Short Rest',
  focusStateLongBreak: 'Closed-Door Retreat',
  focusCompletedSuffix: 'meditation sessions completed',
  focusEmpty: 'The scroll of practice is still blank',
  focusWhiteNoiseOn: 'Pine Winds ON',
  focusWhiteNoiseOff: 'Pine Winds OFF',
  focusTaskLinkLabel: 'Linked Deed',
  mineTitle: 'Satchel',
  mineProductivityScore: 'Jianghu Renown',
  mineSectionShortcuts: 'Quick Access',
  mineSectionSettings: 'Settings',
  mineAllTodos: 'All Jianghu Deeds',
  mineAllHabits: 'All Daily Practices',
  mineDataDetail: 'Satchel Details',
  mineThemeLabel: 'Theme Style',
  mineNotificationsLabel: 'Reminder Preferences',
  mineCloudSyncLabel: 'Cloud Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: 'Meditation Complete',
  notifPomodoroDoneBody: 'A round of practice is done. Go rest awhile.',
  notifBreakDoneTitle: 'Your Rest Has Ended',
  notifBreakDoneBody: 'Ready for another round of practice?',
  notifTodoDueTitle: 'A Deed Comes Due',
  notifHabitRemindTitle: 'Daily Practice Reminder',
);
