// 英文语言变体 — BrandStyle.zzz（绝区零）。
// 全部字段值已翻译为英文（按主题保留各自文案风格）；
// 调整文案时保持字段名与顺序不变（与 BrandStrings 构造器一一对应）。
//
// 声明为顶层 final 而非 const：若用 const，
// Dart 常量规范化（canonicalization）会把值全同的 const 实例合并为
// 同一对象，en 分发将无法在运行时与 zh 区分；final 保证 en 实例
// 独立，供 forLocale 分发与 en 断言验证。
import '../brand_strings.dart';

/// EN 变体（BrandStyle.zzz）。值为英文译文，字段与 zh 常量一一对应。
final BrandStrings enZzz = BrandStrings(
  appTitle: 'Duoyi · Commission Desk',
  greetingMorning: "Mornin', Agent",
  greetingNoon: 'High Noon on the Block',
  greetingAfternoon: 'Neon Afternoon',
  greetingEvening: 'Neon Never Sleeps',
  navToday: 'Shifts',
  navTodo: 'Jobs',
  navHabit: 'Dailies',
  navCalendar: 'Showtimes',
  navFocus: 'Cuts',
  navMine: 'Tapes',
  navWidget: 'Panel',
  todoTitle: 'Commission Board',
  todoMatrixView: 'Neon Grid',
  todoListView: 'Commission List',
  todoEmpty: "Bangboo's got no commissions yet!",
  todoAddAction: 'Grab a New Commission',
  todoCreateTitle: 'New Commission',
  quadrantQ1Label: 'Urgent Ops',
  quadrantQ1Sub: "Hollow's spreading fast",
  quadrantQ2Label: 'Long-Haul Ops',
  quadrantQ2Sub: 'Slow and steady',
  quadrantQ3Label: 'Squad Jobs',
  quadrantQ3Sub: 'Toss it to the crew',
  quadrantQ4Label: 'Shelf It',
  quadrantQ4Sub: 'Let it chill',
  subtasksHeading: 'Side Commissions',
  habitTitle: 'Daily Grind',
  habitTabToday: "Today's Dailies",
  habitTabHeatmap: 'Block Heat',
  habitEmpty: 'No dailies on the books yet',
  habitAddAction: 'Book a New Daily',
  habitCreateTitle: 'New Daily',
  habitWeekOverview: "This Week's Dailies",
  habitHeatmapHeading: 'Block Activity Heat',
  habitStreakLabel: 'Duty Streak',
  habitTodayDone: 'Done for Today',
  calendarTitle: 'Showtimes',
  calendarTabMonth: 'Month',
  calendarTabWeek: 'Week',
  calendarTabDay: 'Day',
  calendarEmpty: 'Nothing booked for this day',
  calendarQuickAddTitle: 'Book a Commission for This Day',
  focusTitle: 'Cutting Room',
  focusTabTimer: 'Cuts',
  focusTabHistory: 'Tapes',
  focusStateFocus: 'Cutting',
  focusStateShortBreak: 'Quick Breather',
  focusStateLongBreak: 'Long Break',
  focusCompletedSuffix: 'cuts in the can',
  focusEmpty: "The tape vault's still empty",
  focusWhiteNoiseOn: 'Street Noise ON',
  focusWhiteNoiseOff: 'Street Noise OFF',
  focusTaskLinkLabel: 'Linked Commission',
  mineTitle: 'Agent Files',
  mineProductivityScore: 'Agent Level',
  mineSectionShortcuts: 'Quick Links',
  mineSectionSettings: 'System',
  mineAllTodos: 'All Commissions',
  mineAllHabits: 'All Dailies',
  mineDataDetail: 'Dossier',
  mineThemeLabel: 'Theme',
  mineNotificationsLabel: 'Notifications',
  mineCloudSyncLabel: 'Cloud Sync',
  mineDataMgmtLabel: 'Data Management',
  mineAboutLabel: 'About Duoyi',
  notifPomodoroDoneTitle: "That's a Wrap!",
  notifPomodoroDoneBody: "Tape's archived — go take five",
  notifBreakDoneTitle: "Break's Over",
  notifBreakDoneBody: 'Ready for the next cut?',
  notifTodoDueTitle: 'Commission Due Soon',
  notifHabitRemindTitle: 'Dailies Check-In',
);
