# Empty Surface Scan (Task 19.2)
#
# 在 Windows / PowerShell 下扫描 `lib/` 里常见的"空架子"信号：
#   - TODO / FIXME / Placeholder / 假数据 / mock / hardcoded 关键字
#   - 函数体只有 `return Container();` / `return const SizedBox();` 的 build
#   - 立即 resolve 的 Future：`async { }` / `Future.value()`
#
# 结果会同时打印到控制台，并覆盖写入 `docs/empty-surface-audit-raw.md`，
# 供人工结合 `lib/core/empty_surface_auditor.dart` 中的 `known` 清单
# 生成正式 backlog `docs/empty-surface-audit.md`。
#
# 用法：
#   pwsh scripts/empty_surface_scan.ps1
#
# 依赖：ripgrep（rg）。如果没有，脚本会回退到 PowerShell 内建的
# `Select-String`，速度慢但无外部依赖。

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$libDir = Join-Path $root 'lib'
if (-not (Test-Path $libDir)) {
    Write-Error "Expected lib/ at repo root ($root). Aborting."
    exit 1
}

$docs = Join-Path $root 'docs'
if (-not (Test-Path $docs)) {
    New-Item -ItemType Directory -Path $docs | Out-Null
}
$outFile = Join-Path $docs 'empty-surface-audit-raw.md'

function Invoke-Scan {
    param(
        [string]$Pattern,
        [string]$Title
    )
    $hasRg = $null -ne (Get-Command rg -ErrorAction SilentlyContinue)
    if ($hasRg) {
        $raw = rg --no-heading --line-number --color never --glob '!**/*.g.dart' --glob '*.dart' -e $Pattern $libDir 2>$null
    }
    else {
        $raw = (Get-ChildItem -Recurse -Path $libDir -Filter *.dart |
            Select-String -Pattern $Pattern |
            ForEach-Object { "$($_.Path):$($_.LineNumber):$($_.Line.Trim())" })
    }
    return [PSCustomObject]@{ Title = $Title; Lines = $raw }
}

$scans = @(
    (Invoke-Scan -Pattern 'TODO|FIXME|XXX' -Title 'TODO / FIXME / XXX 注释'),
    (Invoke-Scan -Pattern '假数据|mock|hardcoded|Placeholder' -Title '假数据 / mock / hardcoded / Placeholder'),
    (Invoke-Scan -Pattern 'return Container\(\);|return const SizedBox\(\);' -Title '空 build：仅 return Container/SizedBox'),
    (Invoke-Scan -Pattern 'Future\.value\(\)|async \{\s*\}' -Title '空 Future（async {} / Future.value()）')
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Empty Surface Audit — Raw Scan Output')
$lines.Add('')
$lines.Add("_Generated by `scripts/empty_surface_scan.ps1` at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')_")
$lines.Add('')

foreach ($s in $scans) {
    $lines.Add("## $($s.Title)")
    $lines.Add('')
    if ($null -eq $s.Lines -or $s.Lines.Count -eq 0) {
        $lines.Add('- (无命中)')
    }
    else {
        foreach ($l in $s.Lines) {
            $lines.Add("- ``$l``")
        }
    }
    $lines.Add('')
}

Set-Content -Path $outFile -Value $lines -Encoding UTF8
Write-Host "Wrote $outFile"
